### ISSUE TITLE
Error when import project

### ISSUE THREAD

**Issue by takaaptech** [solfen/Rogue_Cadet#2]
Hi,
After download and import project into unity, i have this error:

NullReferenceException: Object reference not set to an instance of an object
WeaponSwitcher.Start () (at Assets/Scripts/Weapons/WeaponSwitcher.cs:19)

Can you take a look at that?
Thank!

**Comment by solfen** [comment]
You most likely don't have a save file. It's what's used to know which ship and weapons to spawn.

To create one, first delete the corrupted one you might have. You just have to click on "Delete Save File" in the "Tools" menu.

Then, just launch the "MainMenu" scene, a correct save will be automatically created.

Oh and after that, if you want to modify your save file, to test things (like adding money, changing ship, etc.), you can use the "SaveDebug" object in Unity. It's a SerializedObject in the "Editor" folder. Once the "SaveDebug" is selected, F9 loads the current save into the debug interface, and F10 saves the debug to the real save file.
